### ISSUE TITLE
libGDXを使うべきか

### ISSUE THREAD

**Issue by mmorihiro** [mmorihiro/chat#1]
## libGDXでは機能不足?
今回はチャットのシステムを実装しなければならないし、UIもこれまでと比べて複雑になるだろうからlibGDXでは作るのが難しい...
## Androidのアプリとして
Androidのアプリとして作れば豊富なライブラリを活かして比較的簡単に実装できると思う。と言うか、そうしないと作れない可能性が高い。
ただ、Androidについて学ぶのにはコストもかかってしまうけど、その点についてはどう思う?

**Comment by ciffelia** [comment]
libGDXは低レベルなAPIが多くて複雑なゲームを作るのは難しいと思う。

HTML/CSS/JavaScriptを使ってWebアプリとして制作するっていう手もあるよ。
今回みたいにUIの制作が多い場合には向いてると思う(学習コストはあるけど)
JavaScriptの代わりにKotlinで書くこともできるらしい。

**Comment by mmorihiro** [comment]
アプリと言えばネイティブという発想しかなかったけど、意外とWebアプリもありかも。
ただ、自分は経験がないから学習コストがきついかも。
@prince0203にとってはWebとネイティブだったらどちらの方がやりやすい?

**Comment by ciffelia** [comment]
Webかな、色々作ったことがあるし
学習コストだけど、HTML/CSSは比較的簡単だと思う。JavaScriptはそれと比べると少し難しいかも。
それでもUIを簡単に作れるっていう利点は大きいと思うよ。

**Comment by mmorihiro** [comment]
なら、Webアプリに慣れるために練習用の簡単なアプリを作ってみて、どんな感じか確かめるということにしない?

**Comment by ciffelia** [comment]
そうだね。どんなものを作ってみる？

**Comment by mmorihiro** [comment]
経験がなくてあまりイメージが湧かないんだけど、通信が伴うものがいいと思う。GitHubやQiitaとかのAPIを使って情報を取得して表示するようなのとか。

**Comment by ciffelia** [comment]
そうだね。折角だしチャット風のデザインにしてみない？

**Comment by mmorihiro** [comment]
まあ細かいことは新しいレポジトリを作ってそこで話すということで。このIssueは閉じていいよね?

**Comment by ciffelia** [comment]
:+1:
